#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
unsetopt correct_all
unsetopt correct
setopt clobber
# unsetopt MULTIOS              # disable writing to multiple descriptors.

path=(
  $path
  ~/.local/bin
  ~/.rbenv/bin
  ~/.rbenv/plugins/ruby-build/bin
)
eval "$(rbenv init -)"
typeset -gU path # ensure unique entries only

source /usr/bin/aws_zsh_completer.sh
alias rm='nocorrect rm'
alias ssf='ssh -l fortumo'
alias ssd='grep -T server config/deploy/*'

bindkey "\e\eOD" backward-word
bindkey "\e\eOC" forward-word

# mate-terminal workaround
#if [ "$TERM" = "xterm" ]; then
#  export TERM='xterm-256color'
#fi

export MYDBUSER=imre.lorvi

ssa()
{
	ssh -l fortumo `echo "$@" | sed 's/-/./g'`
}
