#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
unsetopt correct_all
unsetopt correct

export IMREZSHRC=1
source /usr/bin/aws_zsh_completer.sh
alias rm='nocorrect rm'
alias ssf='ssh -l fortumo'
alias ssd='grep -T server config/deploy/*'
alias t='/usr/bin/t --task-dir ~ --delete-if-empty'

bindkey "\e\eOD" backward-word
bindkey "\e\eOC" forward-word

# mate-terminal workaround
if [ "$TERM" = "xterm" ]; then
  export TERM='xterm-256color'
fi

export MYDBUSER=imre.lorvi

export NNN_TMPFILE="/tmp/nnn"

n()
{
        nnn "$@"

        if [ -f $NNN_TMPFILE ]; then
                . $NNN_TMPFILE
                rm $NNN_TMPFILE
        fi
}
